# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"\xab\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x14\n\x0cmail_address\x18\x03 \x01(\t\x12!\n\tuser_type\x18\x04 \x01(\x0e\x32\x0e.User.UserType\"L\n\x08UserType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\x11\n\rADMINISTRATOR\x10\x02\x12\t\n\x05GUEST\x10\x03\x12\x0c\n\x08\x44ISABLED\x10\x04\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\x8d\x01\n\x0fUserTypeRequest\x12,\n\tuser_type\x18\x04 \x01(\x0e\x32\x19.UserTypeRequest.UserType\"L\n\x08UserType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\x11\n\rADMINISTRATOR\x10\x02\x12\t\n\x05GUEST\x10\x03\x12\x0c\n\x08\x44ISABLED\x10\x04\"C\n\x0cUserResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x04user\x18\x03 \x01(\x0b\x32\x05.User\"2\n\x0fUserCntResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x10\n\x08user_cnt\x18\x02 \x01(\r2\xfe\x01\n\x0bUserManager\x12(\n\x07GetUser\x12\x0c.UserRequest\x1a\r.UserResponse\"\x00\x12!\n\x07\x41\x64\x64User\x12\x05.User\x1a\r.UserResponse\"\x00\x12\x37\n\x11\x43ountAlreadyUsers\x12\x0c.UserRequest\x1a\x10.UserCntResponse\"\x00(\x01\x12\x35\n\x0eGetUsersByType\x12\x10.UserTypeRequest\x1a\r.UserResponse\"\x00\x30\x01\x12\x32\n\rGetUsersByIds\x12\x0c.UserRequest\x1a\r.UserResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=15
  _USER._serialized_end=186
  _USER_USERTYPE._serialized_start=110
  _USER_USERTYPE._serialized_end=186
  _USERREQUEST._serialized_start=188
  _USERREQUEST._serialized_end=213
  _USERTYPEREQUEST._serialized_start=216
  _USERTYPEREQUEST._serialized_end=357
  _USERTYPEREQUEST_USERTYPE._serialized_start=110
  _USERTYPEREQUEST_USERTYPE._serialized_end=186
  _USERRESPONSE._serialized_start=359
  _USERRESPONSE._serialized_end=426
  _USERCNTRESPONSE._serialized_start=428
  _USERCNTRESPONSE._serialized_end=478
  _USERMANAGER._serialized_start=481
  _USERMANAGER._serialized_end=735
# @@protoc_insertion_point(module_scope)
